- name: Start zuul_console daemon.
  zuul_console:

- name: debug workspace variables
  debug:
    var: to_debug
  vars:
    to_debug:
      zuul_workspace: "{{ zuul_workspace_root }}"
      executor_src_root: "{{ zuul.executor.src_root }}"

- name: debug current host
  shell: hostname

- name: debug user
  shell: whoami

- name: Synchronize src repos to workspace directory.
  synchronize:
    delete: true
    dest: "{{ zuul_workspace_root }}"
    recursive: true
    src: "{{ zuul.executor.src_root }}"
    owner: no
    group: no
#    rsync_opts:
#    - "-e ssh -i /root/.ssh/id_ed25519"
  no_log: false
