- name: Upload Dell PowerFlex SDC package
  copy:
    src: "{{ powerflex_sdc_deb }}"
    dest: /tmp
  become: yes

- name: Create scini directory 
  file:
    path: /etc/emc/scaleio/scini_sync
    state: directory
    mode: '0755'
  become: yes

- name: Enable On-demand compilation
  file:
    path: /etc/emc/scaleio/scini_sync/.build_scini
    state: touch
  become: yes

- name: Install dependencies
  apt:
    # name: "{{ item }}"
    #with_items: "{{ powerflex_sdc_deps }}"
    name:
      - libnuma1
      - linux-headers-{{ ansible_kernel }}
    update_cache: yes
  become: yes

- name: Install Dell PowerFlex SDC
  apt:
    deb: /tmp/{{ powerflex_sdc_deb }}
  environment:
    MDM_IP: "{{ mdm_ip }}"  
  become: yes

- name: Make sure scini service is running
  systemd:
    name: scini
    state: started
