- name: Create openstack directory
  file:
    path: /opt/emc/scaleio/openstack
    state: directory
    mode: '0755'
  become: yes

- name: Render os-brick connector file
  template:
    src: connector.conf.j2
    dest: /opt/emc/scaleio/openstack/connector.conf
  become: yes

